- site-config/hca-atlas-tracker/local/index/atlasEntityConfig.ts
- site-config/hca-atlas-tracker/local/index/componentAtlasEntityConfig.ts
- site-config/hca-atlas-tracker/local/index/sourceDatasetEntityConfig.ts
> feat: add download to all tables (#15)

- app/components/common/MDXContent/index.tsx
- app/components/common/MDXContent/loginTermsOfService.mdx
- app/components/common/MDXContent/loginText.mdx
- package-lock.json
- package.json
- pages/[entityListType]/index.tsx
- pages/_app.tsx
- pages/login/index.tsx
- site-config/hca-atlas-tracker/dev/authentication/authentication.tsx
- site-config/hca-atlas-tracker/local/config.ts
> feat: configure Google login (#11)

- app/components/Layout/components/Content/content.styles.ts
- app/components/Layout/components/Content/content.tsx
- app/components/common/Content/components/Breadcrumbs/breadcrumbs.styles.ts
- app/components/common/MDXContent/loginTermsOfService.mdx
- app/config/config.ts
- app/content/common/constants.ts
- app/content/common/contentPages.ts
- app/content/common/contentPagesUtils.ts
- app/content/common/entities.ts
- app/content/common/utils.ts
- app/content/hca-atlas-tracker/guides.mdx
- mdx-components.tsx
- next.config.mjs
- package-lock.json
- package.json
- pages/[entityListType]/[...params].tsx
- pages/guides/index.tsx
- site-config/common/entities.ts
- site-config/hca-atlas-tracker/dev/config.ts
- site-config/hca-atlas-tracker/local/config.ts
- site-config/hca-atlas-tracker/prod/config.ts
> feat: create guides stub (#48)

- app/apis/catalog/hca-atlas-tracker/common/api.ts
- app/apis/catalog/hca-atlas-tracker/common/schema.ts
- app/common/utils.ts
- app/components/Detail/components/AddSourceDataset/addSourceDataset.tsx
- app/components/Detail/components/EditAtlas/editAtlas.tsx
- app/components/Detail/components/TrackerForm/components/Section/components/Atlas/components/AuthenticationRequired/authenticationRequired.tsx
- app/components/Detail/components/TrackerForm/components/Section/components/Atlas/components/GeneralInfo/generalInfo.tsx
- app/components/Detail/components/TrackerForm/components/Section/components/SourceDataset/components/GeneralInfo/generalInfo.tsx
- app/components/Detail/components/TrackerForm/trackerForm.styles.ts
- app/components/Detail/components/ViewSourceDatasets/viewSourceDatasets.tsx
- app/routes/constants.ts
- app/views/AddNewAtlasView/common/utils.ts
- app/views/AddNewSourceDatasetView/addNewSourceDatasetView.tsx
- app/views/AddNewSourceDatasetView/common/utils.ts
- app/views/AddNewSourceDatasetView/hooks/useAddSourceDatasetForm.tsx
- app/views/EditAtlasView/common/utils.ts
- app/views/EditAtlasView/hooks/useEditAtlasForm.tsx
- pages/atlases/[atlasId]/source-datasets/create.tsx
> feat: update create source datasets ui (#68)

- app/components/Detail/components/TrackerForm/components/Section/section.styles.ts
- app/components/common/RenderComponents/renderComponents.tsx
- app/components/index.ts
- site-config/hca-atlas-tracker/local/announcements/announcements.ts
- site-config/hca-atlas-tracker/local/authentication/authentication.tsx
- site-config/hca-atlas-tracker/local/config.ts
> feat: configure inactivity logut and notice (#50)

- app/components/Detail/components/AddAtlas/addAtlas.tsx
- app/components/Detail/components/EditAtlas/editAtlas.tsx
- app/hooks/useForm/useForm.ts
- app/views/EditAtlasView/editAtlasView.tsx
- app/views/EditAtlasView/hooks/useEditAtlasForm.tsx
> feat: update buttons on edit atlas form (#76)

- app/apis/catalog/hca-atlas-tracker/common/schema.ts
- app/components/Detail/components/AddAtlas/addAtlas.tsx
- app/components/Detail/components/EditAtlas/editAtlas.tsx
- app/components/Detail/components/TrackerForm/components/Section/components/Atlas/components/GeneralInfo/generalInfo.tsx
- app/components/Detail/components/TrackerForm/components/Section/components/Atlas/components/IntegrationLead/integrationLead.tsx
- app/components/Detail/components/TrackerForm/components/Section/components/SourceDataset/components/GeneralInfo/generalInfo.tsx
- app/components/common/Form/components/FormControl/formControl.styles.ts
- app/components/common/Form/components/Input/input.tsx
- app/components/common/Form/components/Select/select.tsx
- app/views/EditAtlasView/hooks/useEditAtlasForm.tsx
> feat: update new and edit atlas ui with integration lead section (#89)

- app/apis/catalog/hca-atlas-tracker/common/schema.ts
- app/components/Detail/components/AddAtlas/addAtlas.tsx
- app/components/Detail/components/AddSourceDataset/addSourceDataset.tsx
- app/components/Detail/components/EditAtlas/editAtlas.tsx
- app/components/Detail/components/EditSourceDataset/editSourceDataset.tsx
- app/components/Detail/components/TrackerForm/components/Section/components/Atlas/common/constants.ts
- app/components/Detail/components/TrackerForm/components/Section/components/Atlas/components/GeneralInfo/generalInfo.tsx
- app/components/Detail/components/TrackerForm/components/Section/components/Atlas/components/IntegrationLead/integrationLead.tsx
- app/components/Detail/components/TrackerForm/components/Section/components/SourceDataset/components/Add/components/GeneralInfo/generalInfo.tsx
- app/components/Detail/components/TrackerForm/components/Section/components/SourceDataset/components/Edit/components/GeneralInfo/generalInfo.tsx
- app/components/Detail/components/ViewSourceDatasets/viewSourceDatasets.tsx
- app/components/Layout/components/Detail/components/DetailViewHero/components/AtlasStatus/atlasStatus.tsx
- app/hooks/useForm/common/entities.ts
- app/hooks/useForm/useForm.ts
- app/views/EditAtlasView/editAtlasView.tsx
- app/views/EditAtlasView/hooks/useEditAtlasForm.tsx
- app/views/EditSourceDatasetView/editSourceDatasetView.tsx
- app/views/EditSourceDatasetView/hooks/useEditSourceDatasetForm.tsx
- app/views/ViewSourceDatasetsView/viewSourceDatasetsView.tsx
> feat: edit atlases should use the edit api response to populate the edit page (#101)

- app/components/Detail/components/AddSourceDataset/addSourceDataset.tsx
- app/components/Detail/components/EditAtlas/editAtlas.tsx
- app/components/Detail/components/EditSourceDataset/editSourceDataset.tsx
- app/components/Detail/components/TrackerForm/components/Banner/banner.styles.ts
- app/components/Detail/components/TrackerForm/components/Banner/banner.tsx
- app/components/Detail/components/TrackerForm/components/Banner/common/utils.ts
- app/components/Detail/components/TrackerForm/components/Banner/components/FormManagement/formManagement.styles.ts
- app/components/Detail/components/TrackerForm/components/Banner/components/FormManagement/formManagement.tsx
- app/views/EditSourceDatasetView/editSourceDatasetView.tsx
> feat: implement "discard/save" header for edit atalas and source-data set forms (#110)

- app/apis/catalog/hca-atlas-tracker/common/schema.ts
- app/components/Detail/components/EditSourceDataset/editSourceDataset.tsx
- app/components/Detail/components/TrackerForm/components/Section/components/SourceDataset/common/constants.ts
- app/components/Detail/components/TrackerForm/components/Section/components/SourceDataset/components/Edit/components/Identifiers/identifiers.tsx
- app/components/common/Form/components/FormControl/formControl.styles.ts
- app/views/EditSourceDatasetView/hooks/useEditSourceDatasetForm.tsx
- site-config/common/constants.ts
> feat: add identifiers (partial) section to source datasets edit page (#109)

- pages/_app.tsx
> fix: revert session timeout (#121)

- __tests__/api-me.test.ts
- app/apis/catalog/hca-atlas-tracker/common/entities.ts
- app/utils/api-handler.ts
- pages/api/me.ts
~~Moving of database interactions included to hopefully make rebasing with #142 go more cleanly~~
> feat: add /api/me endpoint (#144)

- app/hooks/useFetchAtlas.ts
- app/hooks/useFetchSourceDataset.ts
- app/hooks/useFetchSourceDatasets.ts
- app/providers/authorization.tsx
- app/routes/constants.ts
- app/views/RegistrationRequiredView/registrationRequiredView.tsx
- pages/_app.tsx
- pages/registration-required/index.tsx
> feat: show registration screen only for "unregistered" users. (#165)

- app/components/Detail/components/TrackerForm/components/Section/components/SourceDataset/components/View/components/GeneralInfo/generalInfo.tsx
- app/components/Detail/components/TrackerForm/components/Section/components/SourceDataset/components/View/components/Identifiers/identifiers.tsx
- app/components/common/Form/components/FormLabel/formLabel.styles.ts
- app/components/common/Typography/components/TypographyNoWrap/typographyNoWrap.tsx
- app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts
> feat: add 'visit link' links on the source datasets page for doi and links section (#166)

- package-lock.json
- package.json
- site-config/hca-atlas-tracker/local/index/atlasEntityConfig.ts
- site-config/hca-atlas-tracker/local/index/tasksEntityConfig.ts
> chore: updated latest findable-ui package (#203)

- package-lock.json
- package.json
- site-config/hca-atlas-tracker/local/index/tasksEntityConfig.ts
> feat: canned/pre-saved filters (#206)

- app/components/Detail/components/ViewSourceDatasets/viewSourceDatasets.styles.ts
- app/components/Detail/components/ViewSourceDatasets/viewSourceDatasets.tsx
- app/views/ExploreView/exploreView.styles.ts
- app/views/ExploreView/exploreView.tsx
- site-config/hca-atlas-tracker/local/viewList/subTitleHero.ts
> feat: update atlas table ui (#103)

- app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts
- site-config/hca-atlas-tracker/category.ts
- site-config/hca-atlas-tracker/local/index/atlasEntityConfig.ts
> feat: add basic atlas tasks column (#232)

- app/providers/authorization.tsx
- pages/_app.tsx
> fix: authorizationprovider should mount once (#249)

- app/apis/catalog/hca-atlas-tracker/common/utils.ts
- app/components/Detail/components/AddAtlas/addAtlas.tsx
- app/components/Detail/components/TrackerForm/components/Section/components/Atlas/common/constants.ts
- app/components/Detail/components/TrackerForm/components/Section/components/Atlas/components/Add/components/GeneralInfo/generalInfo.tsx
- app/components/Detail/components/TrackerForm/components/Section/components/Atlas/components/Add/components/IntegrationLead/integrationLead.tsx
- app/components/Detail/components/TrackerForm/components/Section/components/Atlas/components/GeneralInfo/generalInfo.tsx
- app/components/Detail/components/TrackerForm/components/Section/components/Atlas/components/View/components/GeneralInfo/generalInfo.tsx
- app/components/Detail/components/TrackerForm/components/Section/components/Atlas/components/View/components/IntegrationLead/integrationLead.tsx
- app/components/Detail/components/ViewAtlas/viewAtlas.tsx
- app/components/Form/components/Select/components/BioNetwork/bioNetwork.tsx
- app/components/Form/components/Select/components/TargetCompletion/common/constants.ts
- app/components/Form/components/Select/components/TargetCompletion/common/utils.ts
- app/components/Form/components/Select/components/TargetCompletion/targetCompletion.tsx
- app/components/Form/components/Select/components/Wave/wave.tsx
- app/components/Index/components/ViewTasks/components/EditTasks/components/EditTargetCompletion/common/constants.ts
- app/components/Index/components/ViewTasks/components/EditTasks/components/EditTargetCompletion/common/schema.ts
- app/components/Index/components/ViewTasks/components/EditTasks/components/EditTargetCompletion/components/Dialog/components/Content/content.styles.ts
- app/components/Index/components/ViewTasks/components/EditTasks/components/EditTargetCompletion/components/Dialog/components/Content/content.tsx
- app/components/Index/components/ViewTasks/components/EditTasks/components/EditTargetCompletion/editTargetCompletion.tsx
- app/utils/date-fns.ts
- app/views/AddNewAtlasView/common/constants.ts
- app/views/AddNewAtlasView/common/schema.ts
- app/views/AtlasView/common/constants.ts
- app/views/AtlasView/common/schema.ts
- app/views/AtlasView/hooks/useEditAtlasForm.tsx
> feat: add target completion to the atlas view and edit forms (#231)

- app/apis/catalog/hca-atlas-tracker/common/utils.ts
- app/config/utils.ts
- app/utils/date-fns.ts
- app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts
- package-lock.json
- package.json
- site-config/hca-atlas-tracker/local/index/atlasEntityConfig.ts
- site-config/hca-atlas-tracker/local/index/tasksEntityConfig.ts
> feat: fix target completion sorting (#269)

- app/components/Table/components/TableCell/components/TaskCountsCell/taskCountsCell.styles.ts
- app/components/Table/components/TableCell/components/TaskCountsCell/taskCountsCell.tsx
- app/components/index.ts
- app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts
- package-lock.json
- package.json
- site-config/hca-atlas-tracker/local/index/atlasEntityConfig.ts
> feat: link atlas task counts to filtered tasks (#248)

- app/components/Detail/components/TrackerForm/components/Breadcrumbs/common/constants.ts
- app/components/Detail/components/TrackerForm/components/Breadcrumbs/common/utils.ts
- app/components/Detail/components/TrackerForm/components/Section/components/RequestAccess/requestAccess.tsx
- app/components/Layout/components/Detail/components/DetailViewHero/components/BackButton/backButton.styles.ts
- app/components/Layout/components/Detail/components/DetailViewHero/components/BackButton/backButton.tsx
- app/components/Layout/components/Detail/components/DetailViewHero/detailViewHero.tsx
- app/components/common/Form/components/FormManager/components/AccessDeniedPrompt/accessDeniedPrompt.tsx
- app/components/common/Form/components/FormManager/components/AccessPrompt/accessPrompt.tsx
- app/routes/utils.ts
- app/views/AddNewAtlasView/common/utils.ts
- app/views/AddNewComponentAtlasView/common/utils.ts
- app/views/AddNewSourceStudyView/common/utils.ts
- app/views/AtlasView/atlasView.tsx
- app/views/AtlasView/common/utils.ts
- app/views/ComponentAtlasView/common/utils.ts
- app/views/ComponentAtlasView/componentAtlasView.tsx
- app/views/ComponentAtlasesView/common/utils.ts
- app/views/ComponentAtlasesView/componentAtlasesView.tsx
- app/views/SourceDatasetsView/common/utils.ts
- app/views/SourceDatasetsView/sourceDatasetsView.tsx
- app/views/SourceStudiesView/common/utils.ts
- app/views/SourceStudiesView/sourceStudiesView.tsx
- app/views/SourceStudyView/common/utils.ts
- app/views/SourceStudyView/sourceStudyView.tsx
> feat: update breadcrumbs to match new mocks (#272)

- app/utils/crossref/crossref.ts
- migrations/1718924728270_strip-publication-title-html.ts
- package-lock.json
- package.json
Uses [string-strip-html](https://www.npmjs.com/package/string-strip-html), which is installed as part of this PR
> feat: strip html from fields when getting crossref publication (#308)

- package-lock.json
- package.json
- site-config/hca-atlas-tracker/local/index/common/constants.ts
- site-config/hca-atlas-tracker/local/index/tasksEntityConfig.ts
> feat: update ordering on task saved filters (#333)

- app/components/Detail/components/ViewSourceStudies/viewSourceStudies.tsx
- app/components/Detail/components/ViewSourceStudy/components/Tabs/tabs.tsx
- app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts
- app/views/SourceDatasetsView/sourceDatasetsView.tsx
- app/views/SourceStudyView/sourceStudyView.tsx
> feat: add source dataset counts to tabs (#334)

- app/components/Detail/components/TrackerForm/components/Section/components/SourceStudy/components/View/components/GeneralInfo/common/utils.ts
- app/components/Detail/components/TrackerForm/components/Section/components/SourceStudy/components/View/components/GeneralInfo/generalInfo.tsx
- app/components/Detail/components/TrackerForm/components/Section/components/SourceStudy/components/View/components/Identifiers/identifiers.tsx
- app/components/Detail/components/ViewSourceStudy/viewSourceStudy.tsx
- app/views/SourceStudyView/hooks/useEditSourceStudyForm.ts
- app/views/SourceStudyView/hooks/useEditSourceStudyFormManager.ts
- app/views/SourceStudyView/sourceStudyView.tsx
> feat: allow setting of hca, cellxgene and cap urls on source studies with no doi (#359)

- app/components/Detail/components/ViewSourceStudies/viewSourceStudies.tsx
- app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts
> feat: reorder completion indicators to reflect workflow (#341)

- app/hooks/useUserHasEditAuthorization/common/constants.ts
> feat: integration leads can manage integration objects for their atlases - fe (#394)

- package-lock.json
- package.json
> chore: upgrade findable-ui to 15.0.0 (#457)

- package-lock.json
- package.json
- site-config/hca-atlas-tracker/dev/config.ts
- site-config/hca-atlas-tracker/local/config.ts
- site-config/hca-atlas-tracker/prod/config.ts
> feat: add version info to footer (#459)

- app/components/Detail/components/ViewSourceDataset/viewSourceDataset.tsx
- app/components/Detail/components/ViewSourceDatasets/components/RequestAccess/requestAccess.tsx
- app/components/Detail/components/ViewSourceStudy/components/Tabs/tabs.tsx
- app/content/hca-atlas-tracker/validating-atlas-source-study-list.mdx
- app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts
- pages/atlases/[atlasId]/source-studies/[sourceStudyId]/source-datasets.tsx
> feat: rename source study source datasets to "datasets" in ui (#470)

- app/components/Detail/components/TrackerForm/components/Breadcrumbs/common/constants.ts
- app/components/Detail/components/TrackerForm/components/Breadcrumbs/common/utils.ts
- app/views/AddNewComponentAtlasView/common/utils.ts
- app/views/AddNewSourceStudyView/common/utils.ts
- app/views/ComponentAtlasView/common/utils.ts
- app/views/ComponentAtlasesView/common/utils.ts
- app/views/SourceDatasetsView/common/utils.ts
- app/views/SourceStudiesView/common/utils.ts
- app/views/SourceStudyView/common/utils.ts
> feat: include entity lists in breadcrumbs (#471)

- app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts
~~Requires rebasing once #528 is merged~~
Closes #525
> feat: relabel source study title column (#525)

- app/components/Detail/components/ViewAtlasSourceDatasets/viewAtlasSourceDatasets.tsx
- app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts
> feat: link atlas source dataset publication and study and update title label (#524)

- app/services/__mocks__/user-profile.ts
> test: restore user-profile mock to fix tests (#532)

- site-config/hca-atlas-tracker/local/index/atlas/atlasEntityConfig.ts
> feat: update atlas roadmap filter to sort by status and name (#537)

- app/components/Detail/components/ViewAtlasSourceDatasets/viewAtlasSourceDatasets.tsx
- app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts
> feat: remove cellxgene link to make room in atlas source datasets table (#542)

- app/components/Detail/components/ViewAtlasSourceDatasets/viewAtlasSourceDatasets.tsx
- app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts
Icon not included -- I don't think it would be straightforward to add
Closes #549
> feat: add metadata spreadsheet link to atlas source dataset list (#549)

- app/components/Detail/components/TrackerForm/components/Section/components/AtlasSourceDataset/common/constants.ts
Renamed "Metadata spreadsheet" form label to "Metadata entry spreadsheet"
> chore: renamed metadata spreadsheet (#550)

- app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts
- site-config/hca-atlas-tracker/local/index/atlas/atlasEntityConfig.ts
> feat: rename atlas completed status to oc endorsed (#564)

- __tests__/api-atlases-create.test.ts
- app/apis/catalog/hca-atlas-tracker/common/entities.ts
- app/components/Form/components/Select/components/Status/status.tsx
- app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts
- migrations/1737585897954_atlas-status-oc-endorsed.ts
- site-config/hca-atlas-tracker/local/index/atlas/tableOptions.ts
- testing/constants.ts
> feat: rename atlas status value `COMPLETE` to `OC_ENDORSED` (#569)

- app/services/validations.ts
- app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts
> feat: add related entity urls to all validations and show "N/A" when unavailable (#572)

- package-lock.json
- package.json
> fix: update findable ui to resolve issue with tsv export (#573)

- app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts
> feat: update name and content of source study datasets column for more clarity (#585)

- app/components/Detail/components/ViewAtlasSourceDatasets/viewAtlasSourceDatasets.tsx
- app/components/Detail/components/ViewSourceStudies/viewSourceStudies.tsx
- app/components/index.ts
- app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts
> feat: update atlas source study and source dataset tables (#588)

- app/components/Detail/components/ViewAtlas/components/Tabs/tabs.styles.ts
- app/components/Detail/components/ViewAtlas/components/Tabs/tabs.tsx
- app/components/Detail/components/ViewAtlasSourceDatasets/components/Alert/alert.styles.ts
- app/components/Detail/components/ViewAtlasSourceDatasets/components/Alert/alert.tsx
- app/components/Detail/components/ViewAtlasSourceDatasets/components/Alert/constants.ts
- app/components/Detail/components/ViewAtlasSourceDatasets/viewAtlasSourceDatasets.styles.ts
- app/components/Detail/components/ViewAtlasSourceDatasets/viewAtlasSourceDatasets.tsx
- app/components/Detail/components/ViewSourceStudies/components/Alert/alert.styles.ts
- app/components/Detail/components/ViewSourceStudies/components/Alert/alert.tsx
- app/components/Detail/components/ViewSourceStudies/components/Alert/constants.ts
- app/components/Detail/components/ViewSourceStudies/viewAtlasSourceStudies.styles.ts
- app/components/Detail/components/ViewSourceStudies/viewSourceStudies.tsx
- app/components/Layout/components/Detail/detailView.styles.ts
> feat: instructions section for source studies and source dataset (#594)

- app/apis/catalog/hca-atlas-tracker/common/constants.ts
- app/components/Detail/components/ViewSourceStudies/viewSourceStudies.tsx
- app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts
Closes #596
Hopefully this is correct -- wasn't totally clear on what should change/not change
> feat: update source study hca status labels (#596)

- app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts
> fix: enable actual code for source study hca status (#599)

- app/components/Detail/components/ViewAtlasSourceDatasets/viewAtlasSourceDatasets.tsx
- app/components/Detail/components/ViewSourceDatasets/viewSourceDatasets.tsx
- app/components/Detail/components/ViewSourceStudies/viewSourceStudies.tsx
- app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts
> feat: add tier 1 metadata status to source study dataset list (#608)

- .github/ISSUE_TEMPLATE/feedback.md
> chore: added feedback template #604

- app/components/index.ts
- site-config/hca-atlas-tracker/local/config.ts
- site-config/hca-atlas-tracker/local/floating/floating.ts
> feat: add feedback link (#605)

- __tests__/api-atlases-create.test.ts
- __tests__/api-atlases-id-source-datasets-id.test.ts
- __tests__/api-atlases-id.test.ts
- __tests__/get-sheet-title.test.ts
- app/apis/catalog/hca-atlas-tracker/common/backend-utils.ts
- app/apis/catalog/hca-atlas-tracker/common/entities.ts
- app/components/Detail/components/TrackerForm/components/Section/components/AtlasSourceDataset/common/constants.ts
- app/components/Detail/components/ViewAtlasSourceDatasets/viewAtlasSourceDatasets.tsx
- app/services/atlases.ts
- app/services/source-datasets.ts
- app/utils/google-sheets.ts
- app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts
- migrations/1742845443312_source-dataset-metadata-title.ts
- testing/constants.ts
- testing/setup.ts
- testing/utils.ts
> feat: save and display metadata spreadsheet titles for source datasets (#625)

- app/components/Detail/components/ViewAtlas/components/Tabs/tabs.tsx
> feat: swap order of source studies tab and source datasets tab (#638)

- catalog/output/cellxgene-info.json
> chore: update cellxgene tier 1 statuses (#644)

- app/views/AtlasMetadataCorrectnessView/atlasMetadataCorrectnessView.tsx
- app/views/AtlasMetadataEntrySheetValidationView/atlasMetadataEntrySheetValidationView.tsx
- app/views/AtlasMetadataEntrySheetsView/atlasMetadataEntrySheetsView.tsx
- app/views/AtlasSourceDatasetView/atlasSourceDatasetView.tsx
- app/views/AtlasSourceDatasetsView/atlasSourceDatasetsView.tsx
> fix: make atlas source dataset and metadata pages visible to stakeholders (#857)

- __tests__/api-sns-with-s3-event.test.ts
- __tests__/api-sns-with-validation-results.test.ts
- app/services/s3-notification.ts
- app/services/validation-results-notification.ts
- testing/utils.ts
> feat: log invalid json from sns messages (#876)
