README.md, __tests__/api-atlases.test.ts, __tests__/api-users-create.test.ts, __tests__/api-users-id-disable.test.ts, __tests__/api-users-id-enable.test.ts, __tests__/api-users.test.ts, app/utils/__mocks__/pg-connect-config.ts, package.json, scripts/migration-runner.ts, scripts/test-db-migration-runner.ts, testing/global-setup.ts, testing/global-teardown.ts
- Slight change to existing migration runner (ending the pool explicitly to avoid a delay in the script completing)
- Separate test DB migration runner
- Mock for pg-connect-config so that tests will use the test database
=> test: use separate database for tests (#45)

__tests__/api-atlases-create.test.ts, __tests__/api-atlases-id.test.ts, app/apis/catalog/hca-atlas-tracker/common/constants.ts, app/apis/catalog/hca-atlas-tracker/common/entities.ts, app/apis/catalog/hca-atlas-tracker/common/schema.ts, app/apis/catalog/hca-atlas-tracker/common/utils.ts, app/components/Detail/components/TrackerForm/components/Section/components/Atlas/components/GeneralInfo/generalInfo.tsx, app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts, app/views/EditAtlasView/hooks/useEditAtlasForm.tsx, pages/api/atlases/[atlasId].ts, pages/api/atlases/create.ts, site-config/hca-atlas-tracker/category.ts, site-config/hca-atlas-tracker/local/config.ts, site-config/hca-atlas-tracker/local/index/atlasEntityConfig.ts, testing/constants.ts, testing/entities.ts, testing/utils.ts
Note: This PR also updates the atlas `GeneralInfo` to pass `isDirty` props based on `formState`, which means that the edit form will now display input values in gray if they haven't been changed
=> feat: add wave field (#62)

__tests__/api-atlases-create.test.ts, __tests__/api-atlases-id.test.ts, app/apis/catalog/hca-atlas-tracker/common/constants.ts, app/apis/catalog/hca-atlas-tracker/common/entities.ts, app/apis/catalog/hca-atlas-tracker/common/schema.ts, app/apis/catalog/hca-atlas-tracker/common/utils.ts, app/components/Detail/components/TrackerForm/components/Section/components/Atlas/components/GeneralInfo/generalInfo.tsx, app/views/EditAtlasView/hooks/useEditAtlasForm.tsx, pages/api/atlases/[atlasId].ts, pages/api/atlases/create.ts, testing/constants.ts, testing/entities.ts
Also changes the schema to use `oneOf` for network and and wave, meaning the schema is typed more accurately, hence the changes involving type assertions
=> feat: change wave to be a string and be initially unspecified on form (#62)

app/utils/doi.ts
In addition to allowing HTTP URLs as specified in the ticket, this allows URLs with the protocol omitted
=> feat: allow doi urls with http or no protocol (#112)

app/services/cellxgene.ts, app/services/hca-projects.ts, app/utils/cellxgene-api.ts, app/utils/hca-api.ts, package-lock.json, package.json
Retries are done via `ky`, which is made by the same people as `got` but is supposedly preferable because it uses `fetch`
=> feat: add logging and retries to hca/cellxgene refreshes (#140)

app/apis/catalog/hca-atlas-tracker/common/api.ts, app/common/utils.ts, app/components/Detail/components/AddSourceDataset/addSourceDataset.tsx, app/components/Detail/components/EditSourceDataset/editSourceDataset.tsx, app/components/Detail/components/TrackerForm/components/Section/components/SourceDataset/common/constants.ts, app/components/Detail/components/TrackerForm/components/Section/components/SourceDataset/components/Add/components/GeneralInfo/common/utils.ts, app/components/Detail/components/TrackerForm/components/Section/components/SourceDataset/components/Add/components/GeneralInfo/generalInfo.styles.ts, app/components/Detail/components/TrackerForm/components/Section/components/SourceDataset/components/Add/components/GeneralInfo/generalInfo.tsx, app/components/Detail/components/TrackerForm/components/Section/components/SourceDataset/components/Edit/components/GeneralInfo/common/utils.ts, app/components/Detail/components/TrackerForm/components/Section/components/SourceDataset/components/Edit/components/GeneralInfo/generalInfo.styles.ts, app/components/Detail/components/TrackerForm/components/Section/components/SourceDataset/components/Edit/components/GeneralInfo/generalInfo.tsx, app/components/Detail/components/TrackerForm/components/Section/components/SourceDataset/components/Edit/components/Identifiers/identifiers.tsx, app/components/Detail/components/TrackerForm/components/Tabs/tabs.styles.ts, app/components/Detail/components/TrackerForm/components/Tabs/tabs.tsx, app/hooks/useFetchSourceDataset.ts, app/hooks/useForm/common/entities.ts, app/hooks/useForm/useForm.ts, app/views/AddNewSourceDatasetView/common/constants.ts, app/views/AddNewSourceDatasetView/common/entities.ts, app/views/AddNewSourceDatasetView/common/schema.ts, app/views/AddNewSourceDatasetView/hooks/useAddSourceDatasetForm.tsx, app/views/EditSourceDatasetView/common/constants.ts, app/views/EditSourceDatasetView/common/schema.ts, app/views/EditSourceDatasetView/editSourceDatasetView.tsx, app/views/EditSourceDatasetView/hooks/useEditSourceDatasetForm.tsx
Closes #130.
TODOs:
- Should only render form if authenticated with fetched data: should resolve things like the initial tab state ("Published" versus "Unpublished"),
- UI updates to Identifiers section,
- Updates to the disabling of "Save" button (see https://github.com/clevercanary/hca-atlas-tracker/issues/133).
=> feat: create/edit unpublished source datasets ui (#130)

__tests__/api-atlases-id-source-datasets-create.test.ts, app/services/source-datasets.ts, testing/constants.ts
Covers both #139 and #152
Crossref is not called to get DOIs to compare against existing datasets (it'll just compare the given DOI against already-known primary/preprint/journal DOIs) -- do we want to change this and call Crossref to really make sure we don't miss anything?
=> feat: use existing dataset when creating a dataset with an already-used doi (#139, #152)

site-config/hca-atlas-tracker/local/config.ts
=> fix: make help and documentation github link open in new tab (#153)

app/components/Detail/components/ViewSourceDatasets/viewSourceDatasets.tsx
Closes #154.
Sorts source datasets by citation, and then by title (should the citation be the same).
=> feat: sort by publication ascending on source dataset list (#154)

__tests__/api-tasks-completion-dates.test.ts, __tests__/source-dataset-validation-results.test.ts, __tests__/update-validations.test.ts, app/apis/catalog/hca-atlas-tracker/common/schema.ts, app/common/entities.ts, app/services/database.ts, app/services/validations.ts, pages/api/tasks/completion-dates.ts
The endpoint is `/api/tasks/completion-dates` rather than the `/api/tasks/completionDates` specified in the ticket, in order to follow the established naming patterns
=> feat: add api to update target completion dates for tasks (#207)

__tests__/cellxgene.test.ts, __tests__/hca-projects.test.ts, __tests__/revalidate-on-refresh.test.ts, app/services/__mocks__/cellxgene.ts, app/services/__mocks__/hca-projects.ts, app/services/cellxgene.ts, app/services/common/refresh-service.ts, app/services/hca-projects.ts, app/services/refresh-services.ts, app/services/validations.ts, instrumentation.ts
Notes:
- Revalidation happens when either of the refresh services finishes refreshing and there are no other refreshes in progress -- meaning that when both HCA and CELLxGENE get refreshed at the same time, whichever finishes last will trigger revalidation
- Because the server does an initial refresh, revalidation will always happen when the server is started
=> feat: revalidate all source datasets when refresh services finish refreshing (#183)

__tests__/api-atlases-create.test.ts, __tests__/api-atlases-id.test.ts, __tests__/cellxgene.test.ts, __tests__/hca-projects.test.ts, __tests__/refresh-validations.test.ts, __tests__/revalidate-on-refresh.test.ts, app/apis/catalog/hca-atlas-tracker/common/entities.ts, app/apis/catalog/hca-atlas-tracker/common/utils.ts, app/services/atlases.ts, app/services/cellxgene.ts, app/services/hca-projects.ts, app/services/validations.ts, migrations/1716345988615_atlas-task-counts.ts, pages/api/atlases/[atlasId].ts, pages/api/atlases/create.ts, testing/db-utils.ts, testing/utils.ts
Task counts are updated in the migration and after a full revalidation
=> feat: add task counts to atlases (#212)

app/components/common/MDXContent/confidentialNotice.mdx, app/components/common/MDXContent/index.tsx, app/components/index.ts, site-config/hca-atlas-tracker/local/index/atlasEntityConfig.ts, site-config/hca-atlas-tracker/local/viewList/subTitleHero.ts
=> feat: add confidentiality notice (#211)

app/components/Detail/components/TrackerForm/components/Section/components/SourceDataset/common/constants.ts, app/components/Detail/components/TrackerForm/components/Section/components/SourceDataset/components/View/components/Identifiers/identifiers.tsx, app/components/Form/common/entities.ts, app/components/Form/common/utils.ts, app/components/Form/components/Input/components/CapId/capId.tsx, app/components/Form/components/Input/components/CapId/common/constants.ts, app/components/common/Form/components/FormHelperText/formHelperText.styles.ts, app/views/AddNewSourceDatasetView/hooks/useAddSourceDatasetFormManager.tsx, app/views/SourceDatasetView/common/constants.ts, app/views/SourceDatasetView/common/schema.ts, app/views/SourceDatasetView/hooks/useEditSourceDatasetForm.tsx, app/views/SourceDatasetView/hooks/useEditSourceDatasetFormManager.tsx
=> feat: add cap url to source dataset edit page (#255)

__tests__/api-atlases-id-source-studies-id-source-datasets-create.test.ts, __tests__/api-atlases-id-source-studies-id-source-datasets-id.test.ts, __tests__/api-atlases-id-source-studies-id-source-datasets.test.ts, __tests__/cellxgene.test.ts, __tests__/hca-projects.test.ts, __tests__/revalidate-on-refresh.test.ts, __tests__/update-cellxgene-source-datasets.test.ts, app/apis/catalog/hca-atlas-tracker/common/entities.ts, app/apis/catalog/hca-atlas-tracker/common/schema.ts, app/apis/catalog/hca-atlas-tracker/common/utils.ts, app/services/__mocks__/cellxgene.ts, app/services/cellxgene.ts, app/services/database.ts, app/services/hca-projects.ts, app/services/refresh-services.ts, app/services/source-datasets.ts, app/services/source-studies.ts, app/utils/api-handler.ts, app/utils/cellxgene-api.ts, migrations/1717735890311_source-dataset-table.ts, pages/api/atlases/[atlasId]/source-studies/[sourceStudyId]/source-datasets.ts, pages/api/atlases/[atlasId]/source-studies/[sourceStudyId]/source-datasets/[sourceDatasetId].ts, pages/api/atlases/[atlasId]/source-studies/[sourceStudyId]/source-datasets/create.ts, testing/constants.ts, testing/db-utils.ts, testing/entities.ts
Should updating CELLxGENE source datasets be done with transactions of any sort? Currently each dataset is inserted/updated individually
=> feat: add source datasets backend (#274)

app/utils/doi.ts, migrations/1718484744990_trim-doi-whitespace.ts
(This will not cause HCA/CELLxGENE IDs to be recalculated, as they're only updated when the source study is edited)
=> feat: trim whitespace from normalized dois (#305)

app/components/Detail/components/ViewAtlas/components/Tabs/tabs.tsx
=> feat: add count of component atlases to component atlas tab similar to source study count (#288)

__tests__/api-comments-thread-id-comments-comment-id.test.ts, __tests__/api-comments-thread-id-comments.test.ts, __tests__/api-comments.test.ts, app/apis/catalog/hca-atlas-tracker/common/entities.ts, app/apis/catalog/hca-atlas-tracker/common/schema.ts, app/apis/catalog/hca-atlas-tracker/common/utils.ts, app/services/comments.ts, app/utils/api-handler.ts, migrations/1719273460285_comment-table.ts, pages/api/comments.ts, pages/api/comments/[threadId]/comments.ts, pages/api/comments/[threadId]/comments/[commentId].ts, testing/constants.ts, testing/db-utils.ts, testing/entities.ts
APIs added:
- `/api/comments`
- POST to create a thread, with body of shape `{ text: string }`, specifying the text of the root comment
- `/api/comments/[threadId]/comments`
- GET to get all comments in the thread, ordered by timestamp
- POST to create a new comment in the thread, with body of shape `{ text: string }`
- `/api/comments/[threadId]/comments/[commentId]`
- GET to get a comment
- PATCH to update a comment, with body of shape `{ text: string }`; only content admins can update other users' comments
- DELETE to delete a comment, or an entire thread if the root comment is requested; only content admins can delete other users' comments or delete root comments
All are restricted to registered users
=> feat: add comments table and apis (#292)

__tests__/api-comments-thread-id-comments-comment-id.test.ts, __tests__/api-tasks-validation-id-comment.test.ts, __tests__/update-validations.test.ts, app/apis/catalog/hca-atlas-tracker/common/entities.ts, app/apis/catalog/hca-atlas-tracker/common/utils.ts, app/services/comments.ts, app/services/validations.ts, migrations/1719633686503_validation-comment-thread-property.ts, pages/api/tasks/[validationId]/comment.ts
Adds POST and DELETE for `/api/tasks/[validationId]/comment`, as well as removing the ability to DELETE `/api/comments/[threadId]/comments/[commentId]`
=> feat: add task comment apis (#347)

__tests__/api-atlases-id-component-atlases-id-source-datasets-id.test.ts, __tests__/api-atlases-id-source-studies-id-source-datasets-id.test.ts, __tests__/api-atlases-id-source-studies-id.test.ts, __tests__/revalidate-on-refresh.test.ts, __tests__/update-cellxgene-source-datasets.test.ts, __tests__/update-component-atlas-aggregate-fields-on-refresh.test.ts, app/apis/catalog/hca-atlas-tracker/common/entities.ts, app/apis/catalog/hca-atlas-tracker/common/utils.ts, app/components/Detail/components/ViewComponentAtlases/viewComponentAtlases.tsx, app/services/component-atlases.ts, app/services/refresh-services.ts, app/services/source-datasets.ts, app/services/source-studies.ts, app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts, migrations/1720034230795_component-atlas-dataset-properties.ts, testing/constants.ts, testing/db-utils.ts, testing/entities.ts, testing/utils.ts
A component atlas's properties are updated when:
- The new migration is run
- A source dataset is added to it
- A source dataset is removed from it
- One of its CELLxGENE source datasets is updated after a refresh
=> feat: add component atlas fields aggregated from source datasets (#350)

__tests__/api-atlases-id-source-studies-id-source-datasets-create.test.ts, __tests__/api-atlases-id-source-studies-id-source-datasets-id.test.ts, pages/api/atlases/[atlasId]/source-studies/[sourceStudyId]/source-datasets/[sourceDatasetId].ts, pages/api/atlases/[atlasId]/source-studies/[sourceStudyId]/source-datasets/create.ts
In addition to allowing creating and deleting source datasets as specified in the ticket, also allows editing source datasets (i.e. editing their titles)
=> feat: allow integration leads to use source dataset apis for their atlases (#370)

__tests__/api-users-integration-leads-from-atlases.test.ts, app/components/Forms/components/IntegrationLeadsFromAtlases/integrationLeadsFromAtlases.tsx, app/services/atlases.ts, app/services/users.ts, app/views/IntegrationLeadsFromAtlasesView/integrationLeadsFromAtlasesView.tsx, pages/api/users/integration-leads-from-atlases.ts, pages/integration-leads-from-atlases/index.tsx, testing/constants.ts
New API is PATCH `/api/users/integration-leads-from-atlases`, useable by content admins
New page `/integration-leads-from-atlases` allows calling the API
=> feat: add api and page to update integration lead users from atlases (#376)

app/routes/constants.ts, app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts, next.config.mjs, site-config/hca-atlas-tracker/local/config.ts, site-config/hca-atlas-tracker/local/index/tasks/tasksEntityConfig.ts
It doesn't seem to be possible to change the label of the saved filters
=> feat: rename tasks list to reports (#377)

__tests__/api-atlases-id-source-studies-create.test.ts, __tests__/api-atlases-id-source-studies-id.test.ts, __tests__/api-atlases-id-source-studies.test.ts, app/apis/catalog/hca-atlas-tracker/common/entities.ts, app/apis/catalog/hca-atlas-tracker/common/utils.ts, app/components/Table/components/TableCell/components/SourceStudyStatusCell/sourceStudyStatusCell.tsx, app/services/database.ts, app/services/source-studies.ts, app/services/validations.ts, app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts, testing/db-utils.ts, testing/utils.ts
The validations returned with source studies don't have atlas-related information included, which is in line with the example response given in the ticket but does mean there's some non-duplicate information that is not included (namely, what other atlases the source study is in)
=> feat: derive source study status columns from validations (#386)

__tests__/api-atlases-create.test.ts, __tests__/api-atlases-id-component-atlases-create.test.ts, __tests__/api-atlases-id-component-atlases-id.test.ts, __tests__/api-atlases-id-component-atlases.test.ts, __tests__/api-atlases-id.test.ts, app/apis/catalog/hca-atlas-tracker/common/entities.ts, app/apis/catalog/hca-atlas-tracker/common/schema.ts, app/apis/catalog/hca-atlas-tracker/common/utils.ts, app/services/atlases.ts, app/services/component-atlases.ts, migrations/1722625517148_description-fields.ts, testing/constants.ts, testing/db-utils.ts, testing/entities.ts, testing/utils.ts
Create and edit APIs for atlases and integration objects accept an optional `description` field, which is limited to 10000 characters by the validator
=> feat: add description fields to atlases and integration objects (#406)

__tests__/api-tasks-completion-dates.test.ts, __tests__/api-tasks.test.ts, __tests__/refresh-validations.test.ts, __tests__/source-study-validation-results.test.ts, app/apis/azul/hca-dcp/common/entities.ts, app/apis/catalog/hca-atlas-tracker/common/constants.ts, app/apis/catalog/hca-atlas-tracker/common/entities.ts, app/components/Index/components/ViewTasks/components/PreviewTask/components/Section/components/Description/description.tsx, app/services/source-studies.ts, app/services/validations.ts, app/utils/hca-projects.ts, site-config/hca-atlas-tracker/local/index/tasks/tasksEntityConfig.ts, testing/constants.ts, testing/db-utils.ts, testing/utils.ts
- Source studies provided to validations now have some atlas properties attached
- Differences listed in validation results can now be arrays, in which case, in the app, the values from `expected` that are missing from `actual` are displayed
- Networks are compared case-insensitively, since they're stored in lowercase in the tracker but appear to be capitalized in the data browser
=> feat: add validation for hca project networks and atlases (#419)

__tests__/api-users-create.test.ts, __tests__/api-users-id.test.ts, app/views/AddNewUserView/common/schema.ts, app/views/UserView/common/schema.ts, pages/api/users/create.ts
I've removed the "strict" setting from the forms' schemas, which allows the email to be automatically trimmed before being sent to the API; as far as I know removing that setting won't have any other effects -- I believe it's a carryover from the API schemas, where we wanted to prevent values of the wrong type from being cast to the correct type and thus accepted
(Note: I've also tacked on a change to the user create handler, because I came across an issue where a validation error that happened server-side didn't get returned to the client)
=> feat: trim whitespace from email in user forms (#429)

app/components/Detail/components/TrackerForm/components/Section/components/SourceStudy/common/constants.ts
- Replaced the one instance of "DOI no." with "DOI"
=> chore: removed the 'no.' after 'DOI no.' (#469)

app/apis/catalog/hca-atlas-tracker/common/utils.ts, app/components/Detail/components/TrackerForm/components/Section/components/ComponentAtlas/common/constants.ts, app/components/Detail/components/TrackerForm/components/Section/components/ComponentAtlas/components/GeneralInfo/generalInfo.tsx, app/components/Detail/components/TrackerForm/components/Section/components/SourceDataset/common/constants.ts, app/components/Detail/components/TrackerForm/components/Section/components/SourceDataset/components/GeneralInfo/generalInfo.tsx, app/components/Detail/components/TrackerForm/components/Section/components/TrackerFormSection/trackerFormSection.tsx, app/components/Forms/components/Atlas/common/constants.ts, app/components/common/Form/components/Controllers/common/entities.ts, app/components/common/Form/components/Controllers/components/InputController/inputController.tsx, app/components/common/Form/components/Controllers/controllers.tsx, app/services/atlases.ts, app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts, app/views/AddNewAtlasView/common/constants.ts, app/views/AddNewAtlasView/common/schema.ts, app/views/AddNewAtlasView/hooks/useAddAtlasForm.ts, app/views/AtlasView/hooks/useEditAtlasForm.ts
The backend already supports atlas DOIs/publications; each atlas technically can have multiple publications, which I've kept as-is while making the forms only support setting 1 or 0 DOIs
=> feat: add doi input to atlas forms (#485)

app/views/SourceStudyView/hooks/useEditSourceStudyFormManager.ts
Closes #496
Turns out the fields *were* getting unregistered, but were being added back by `mapPayload`
=> fix: avoid error when saving published source study (#496)

app/components/Detail/components/ViewAtlasSourceDatasets/viewAtlasSourceDatasets.tsx, app/components/Index/components/FileDownload/fileDownload.tsx, app/components/index.ts, app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts
Closes #526
- URL are constructed under the assumption that for any dataset version ID there will be a file with a URL of the form `https://datasets.cellxgene.cziscience.com/${versionId}.h5ad` (this appears to be the case for all current datasets on CELLxGENE)
- Only the atlas source datasets list has the download button
=> feat: add download buttons to atlas source datasets (#526)

site-config/hca-atlas-tracker/local/index/tasks/column.ts, site-config/hca-atlas-tracker/local/index/tasks/tableOptions.ts
Closes #538
In addition to multi-valued fields and dates, I've left out entity type, since we only have validations for source studies
=> feat: add additional grouping options for tasks and remove default grouping (#538)

site-config/hca-atlas-tracker/local/index/atlas/atlasEntityConfig.ts, site-config/hca-atlas-tracker/local/index/atlas/tableOptions.ts
- Set the default table settings to group by roadmap and sort first by status then by name
=> feat: added roadmap grouping by default (#546)

site-config/hca-atlas-tracker/local/index/tasks/columns.ts, site-config/hca-atlas-tracker/local/index/tasks/tableOptions.ts
I've left the column hidden by default because it seems tricky to have it visible with the current column layout while keeping target completion in view
=> feat: add resource column to reports table (#571)

__tests__/api-atlases-create.test.ts, __tests__/api-atlases-id.test.ts, app/apis/catalog/hca-atlas-tracker/common/backend-utils.ts, app/apis/catalog/hca-atlas-tracker/common/entities.ts, app/apis/catalog/hca-atlas-tracker/common/schema.ts, app/apis/catalog/hca-atlas-tracker/common/utils.ts, app/components/Detail/components/TrackerForm/components/Breadcrumbs/common/constants.ts, app/components/Detail/components/TrackerForm/components/Breadcrumbs/common/utils.ts, app/components/Detail/components/ViewAtlas/components/Tabs/tabs.tsx, app/components/Detail/components/ViewAtlasMetadataCorrectness/components/RequestAccess/requestAccess.tsx, app/components/Detail/components/ViewAtlasMetadataCorrectness/vewAtlasMetadataCorrectness.styles.ts, app/components/Detail/components/ViewAtlasMetadataCorrectness/viewAtlasMetadataCorrectness.tsx, app/components/Forms/components/Atlas/common/constants.ts, app/routes/constants.ts, app/services/atlases.ts, app/views/AtlasMetadataCorrectnessView/atlasMetadataCorrectnessView.tsx, app/views/AtlasMetadataCorrectnessView/common/utils.ts, app/views/AtlasView/common/constants.ts, app/views/AtlasView/common/schema.ts, app/views/AtlasView/hooks/useEditAtlasForm.ts, migrations/1738635767121_atlas-metadata-correctness.ts, pages/atlases/[atlasId]/metadata-correctness/index.tsx, testing/constants.ts, testing/entities.ts, testing/utils.ts
Wasn't sure exactly what the page should look like -- ~~here's what I have (EDIT: aside from the breadcrumbs which I have fixed):~~
=> feat: add metadata correctness report to atlas detail (#578)

@types/theme.d.ts, app/apis/catalog/hca-atlas-tracker/common/constants.ts, app/apis/catalog/hca-atlas-tracker/common/utils.ts, app/components/Detail/components/ViewSourceStudies/viewSourceStudies.tsx, app/components/Table/components/TableCell/components/SourceStudyStatusCell/sourceStudyStatusCell.styles.ts, app/components/Table/components/TableCell/components/SourceStudyStatusCell/sourceStudyStatusCell.tsx, app/components/common/CustomIcon/components/PartiallyCompleteIcon/partiallyCompleteIcon.tsx, app/components/common/CustomIcon/components/RequiredIcon/requiredIcon.tsx, app/theme/common/components.ts, app/theme/theme.ts, app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts, site-config/hca-atlas-tracker/local/config.ts
Notes on contents:
- I've adjusted a couple of the labels ("To do" and "Complete") to be consistent with task statuses
- The HCA status is set as "Primary data blocked" if the ingest task is `DONE` and the primary data task is`BLOCKED` -- not certain this is exactly how it will end up working, as currently there's no way for the primary data task to have the `BLOCKED` status, but I believe the plan is to in the future allow primary data to be set as blocked
- Despite the mock showing "In progress" as a possibility for HCA status, I didn't include it as a possibility for HCA here, since to my knowledge there's no current or planned way of setting the HCA ingest task or the primary data task as being in progress
Other considerations:
The colors are not entirely accurate to the mock -- the …
=> feat: incorporate primary data status into source study hca status (#589)

README.md, catalog/build/get_cellxgene_files_info.py, catalog/output/cellxgene-info.json
Closes #610
In theory the only missing datasets should be:
- 53d208b0-2cfd-4366-9866-c3c6114081bc ([Tabula Sapiens - All Cells](https://cellxgene.cziscience.com/collections/e5f58829-1a66-40b5-a624-9046778e74f5))
- c5d88abe-f23a-45fa-a534-788985e93dad (Tabula Sapiens - Immune)
- 0129dbd9-a7d3-4f6b-96b9-1da155a93748 ([All major cell types in adult human retina](https://cellxgene.cziscience.com/collections/af893e86-8e9f-41f1-a474-ef05359b1fb7))
=> content: update tier 1 metadata info (#610)

__mocks__/googleapis.ts, __tests__/api-atlases-create.test.ts, __tests__/api-atlases-id.test.ts, __tests__/get-sheet-title.test.ts, app/apis/catalog/hca-atlas-tracker/common/backend-utils.ts, app/apis/catalog/hca-atlas-tracker/common/entities.ts, app/apis/catalog/hca-atlas-tracker/common/schema.ts, app/apis/catalog/hca-atlas-tracker/common/utils.ts, app/components/Forms/components/Atlas/common/constants.ts, app/components/common/Form/components/Input/input.tsx, app/services/atlases.ts, app/utils/google-sheets.ts, app/views/AtlasView/common/schema.ts, migrations/1742536132066_metadata-specification-title.ts, package-lock.json, package.json, site-config/hca-atlas-tracker/dev/.env, site-config/hca-atlas-tracker/local/.env, site-config/hca-atlas-tracker/prod/.env, testing/constants.ts, testing/setup.ts, testing/utils.ts
Closes #602
Notes:
- The email specified in the error for when the sheet is unshared is determined by an environment variable so that it can vary between dev and prod
- In order to make it so the full error message is visible, I've made it so that all error messages on form inputs have wrapping text (however, other helper text still has hidden overflow by default -- see screenshots below)
One thing I'm wondering about -- does it matter that the form data has to be edited in order to save it and update the sheet title?
---
Example wrapping error message:
---
Example truncated sheet title:
=> feat: query, save, and display metadata specification sheet title in atlas form (#602)

__tests__/update-cellxgene-source-datasets.test.ts, app/services/source-datasets.ts, testing/constants.ts, testing/entities.ts, testing/utils.ts
Closes #629
- Updated test to check that metadata spreadsheet info is retained when a dataset is updated
- Made it so that source dataset info derived from CELLxGENE only includes the fields that actually come from CELLxGENE; for an updated dataset this gets merged into the existing info, and for a new dataset this is used to derive a full source dataset info object including metadata spreadsheet fields set to `null`
=> fix: retain metadata spreadsheet info when cellxgene dataset is updated (#629)

__tests__/api-atlases-id-source-studies-id.test.ts, app/apis/catalog/hca-atlas-tracker/common/schema.ts, app/components/Form/components/Input/components/CapId/capId.tsx, app/components/Form/components/Input/components/CapId/common/constants.ts, app/views/SourceStudyView/common/schema.ts, testing/constants.ts
Closes #649
Also updates the backend to restrict CAP URLs by the regex, which was not being done before -- was there a reason for that?
=> fix: accept project urls for cap id rather than dataset urls (#649)

__tests__/api-atlases-id-entry-sheet-validations.test.ts, app/apis/catalog/hca-atlas-tracker/common/backend-utils.ts, app/apis/catalog/hca-atlas-tracker/common/entities.ts, app/services/entry-sheets.ts, app/services/source-studies.ts, pages/api/atlases/[atlasId]/entry-sheet-validations.ts
=> feat: add api to get entry sheet validations of an atlas (#656)

__tests__/api-atlases-id-entry-sheet-validations-id.test.ts, app/apis/catalog/hca-atlas-tracker/common/backend-utils.ts, app/apis/catalog/hca-atlas-tracker/common/entities.ts, app/services/entry-sheets.ts, pages/api/atlases/[atlasId]/entry-sheet-validations/[entrySheetValidationId].ts
Closes #658
The API route is `/api/atlases/[atlasId]/entry-sheet-validations/[entrySheetValidationId]`, notably deviating from the ticket (as I understand it) by using the ID of the saved entry sheet validation rather than the ID of the Google Sheet
=> feat: add api to get a full individual entry sheet validation (#658)

app/services/atlases.ts, app/services/entry-sheets.ts, app/services/source-studies.ts, app/utils/hca-validation-tools/hca-validation-tools-api.ts, app/utils/hca-validation-tools/hca-validation-tools.ts
This pull request introduces changes to improve the handling of atlas-related data and validation processes. The key updates include the addition of a new function to retrieve atlas details, enhancements to source study retrieval logic, and modifications to validation tools to incorporate network-specific parameters.
* [`app/services/atlases.ts`](diffhunk://#diff-a1c3105bef5b2c384d969f03ebcad8efaa13292522f9e2fa19ee42a882fa3971R57-R70): Added `getBaseModelAtlas` function to retrieve atlas details by ID, including error handling for non-existent IDs.
* [`app/services/source-studies.ts`](diffhunk://#diff-e0d65380741c0fdf3ed85ad3832072c98c1e0a9f0e1c50178912c8f01caa1f59L83-R106): Refactored `getBaseModelAtlasSourceStudies` to use the new `getBaseModelAtlas` function and introduced …
=> feat: send bionetwork in validation tools requests (#674)

__tests__/api-atlases-id.test.ts, __tests__/api-atlases.test.ts, app/apis/catalog/hca-atlas-tracker/common/backend-utils.ts, app/apis/catalog/hca-atlas-tracker/common/entities.ts, app/apis/catalog/hca-atlas-tracker/common/utils.ts, app/services/atlases.ts, testing/constants.ts
Closes #678
I initially thought that getting entry sheet validation count would be awkward and would require involving the source studies table, but it's actually relatively simple since both atlases and entry sheet validations store source study IDs and so you can just join based on that, which is what I've done
=> feat: return entry sheet validation count from atlas apis (#678)

app/components/Detail/components/ViewAtlas/components/Tabs/tabs.tsx
Closes #676.
This pull request updates the `Tabs` component in `tabs.tsx` to enhance the display of tab labels by including dynamic counts for entry sheet validations. The most important changes are as follows:
* Updated the destructuring of the `atlas` object to include `entrySheetValidationCount`, enabling the use of this count in the tab labels. (`[app/components/Detail/components/ViewAtlas/components/Tabs/tabs.tsxL25-R26](diffhunk://#diff-1108c3d735aac7a45e5785895f31fe25f2f91e87827bcdc7a21d6d0a0f9d9e83L25-R26)`)
* Modified the "Metadata Entry Sheets" tab label to dynamically display the count of entry sheet validations using the `getTabLabelWithCount` function. (`[app/components/Detail/components/ViewAtlas/components/Tabs/tabs.tsxL44-R48](diffhunk://#diff-1108c3d735aac7a45e5785895f31fe …
=> feat: add count to metadata entry sheet tab (#676)

app/components/common/Paper/components/FluidPaper/fluidPaper.styles.ts, app/components/common/Paper/components/FluidPaper/fluidPaper.tsx, app/components/common/Paper/components/RoundedPaper/roundedPaper.styles.ts, app/components/common/Paper/components/RoundedPaper/roundedPaper.tsx, app/views/AtlasMetadataEntrySheetsView/common/config.ts, app/views/AtlasMetadataEntrySheetsView/common/constants.ts, app/views/AtlasMetadataEntrySheetsView/components/Summary/constants.ts, app/views/AtlasMetadataEntrySheetsView/components/Summary/entities.ts, app/views/AtlasMetadataEntrySheetsView/components/Summary/summary.styles.ts, app/views/AtlasMetadataEntrySheetsView/components/Summary/summary.tsx, app/views/AtlasMetadataEntrySheetsView/components/Summary/utils.ts, app/views/AtlasMetadataEntrySheetsView/components/Table/table.tsx
Closes #682.
This pull request introduces reusable styled components for `Paper` elements and integrates a new `Summary` component into the `AtlasMetadataEntrySheetsView`. The changes improve code modularity, reusability, and the visual presentation of metadata summaries.
* Added `RoundedPaper` and `FluidPaper` components with custom styles for consistent UI elements. These components are now used in various parts of the application. (`fluidPaper.styles.ts` - [[1]](diffhunk://#diff-d43f85b88d9b96992adc1430a6514bd16f986d14a4cb487b28a399bb3ef568ecR1-R12) `fluidPaper.tsx` - [[2]](diffhunk://#diff-efc6a0fa9947624245fd603f0cad4d92bb1d59543777973f5626118c1a23cb74R1-R9) `roundedPaper.styles.ts` - [[3]](diffhunk://#diff-2610e590c09eaf9f254565a1c4993a56ea51c81e7a3b2e306cf2d40c47817f24R1-R10) …
=> feat: add summary to metadata entry sheets (#682)

app/components/common/Button/components/ButtonLink/buttonLink.tsx, app/views/AtlasMetadataEntrySheetsView/atlasMetadataEntrySheetsView.tsx, app/views/AtlasMetadataEntrySheetsView/common/config.ts, app/views/AtlasMetadataEntrySheetsView/common/constants.ts, app/views/AtlasMetadataEntrySheetsView/components/Alert/alert.styles.ts, app/views/AtlasMetadataEntrySheetsView/components/Alert/alert.tsx
Closes #683.
This pull request introduces updates to enhance the functionality and user experience of the `AtlasMetadataEntrySheetsView` and its related components. The key changes include improvements to the `ButtonLink` component, the addition of a new `Alert` component, and updates to the metadata entry sheets configuration.
* Modified the `href` property in `ButtonLinkProps` to accept both `string` and `LinkProps["href"]`, improving flexibility when defining link destinations. (`app/components/common/Button/components/ButtonLink/buttonLink.tsx`, [app/components/common/Button/components/ButtonLink/buttonLink.tsxL18-R19](diffhunk://#diff-21dc7aa6064fc16c275916ec2c1e821ca0d4734500b243788be41d405db078dfL18-R19))
* Introduced a new `Alert` component with styled properties and an action …
=> feat: add alert to metadata entry sheets (#683)

app/apis/catalog/hca-atlas-tracker/common/api.ts, app/views/AtlasMetadataEntrySheetValidationView/atlasMetadataEntrySheetValidationView.tsx, app/views/AtlasMetadataEntrySheetValidationView/components/Actions/actions.tsx, app/views/AtlasMetadataEntrySheetValidationView/hooks/UseEntrySheetSync/hook.ts, app/views/AtlasMetadataEntrySheetValidationView/hooks/UseEntrySheetSync/types.ts, app/views/AtlasMetadataEntrySheetValidationView/hooks/UseEntrySheetSync/utils.ts, app/views/AtlasMetadataEntrySheetsView/atlasMetadataEntrySheetsView.tsx, app/views/AtlasMetadataEntrySheetsView/hooks/UseEntrySheetSync/hook.ts, app/views/AtlasMetadataEntrySheetsView/hooks/UseEntrySheetSync/types.ts, app/views/AtlasMetadataEntrySheetsView/hooks/UseEntrySheetSync/utils.ts
Closes #713
Note: I renamed some existing things from the atlas entry sheets sync to avoid ambiguity
=> feat: add sync button to entry sheet validation view (#713)

app/components/Detail/components/ViewAtlasSourceDatasets/constants.ts, app/components/Detail/components/ViewComponentAtlases/constants.ts, app/components/Detail/components/ViewSourceDatasets/constants.ts, app/components/Detail/components/ViewSourceStudies/constants.ts, app/views/AtlasMetadataEntrySheetValidationView/components/ValidationReport/components/Alert/alert.styles.ts, app/views/AtlasMetadataEntrySheetValidationView/components/ValidationReport/components/Alert/alert.tsx, app/views/AtlasMetadataEntrySheetValidationView/components/ValidationReport/components/EntityValidationReport/entityValidationReport.tsx, app/views/AtlasMetadataEntrySheetsView/common/constants.ts, package-lock.json, package.json
Closes #723.
This pull request introduces several updates across the codebase, focusing on improving table configurations, enhancing UI components, and updating dependencies. The most significant changes include adding `getRowId` to various table configurations, refactoring the `Alert` component to include clickable links, and upgrading the `@databiosphere/findable-ui` dependency.
* Added `getRowId` to the `TABLE_OPTIONS` in multiple files to standardize row identification for tables. (`app/components/Detail/components/ViewAtlasSourceDatasets/constants.ts`, `app/components/Detail/components/ViewComponentAtlases/constants.ts`, `app/components/Detail/components/ViewSourceDatasets/constants.ts`, `app/components/Detail/components/ViewSourceStudies/constants.ts`, …
=> feat: validation report - link column name to data dictionary (#723)

app/views/AtlasMetadataEntrySheetValidationView/components/ValidationReport/components/Alert/alert.tsx, app/views/AtlasMetadataEntrySheetValidationView/components/ValidationReport/components/Alert/constants.ts, app/views/AtlasMetadataEntrySheetValidationView/components/ValidationReport/components/Alert/entities.ts, app/views/AtlasMetadataEntrySheetValidationView/components/ValidationReport/components/EntityValidationReport/entityValidationReport.tsx, package-lock.json, package.json
Closes #732.
This pull request introduces changes to improve the handling of metadata URLs in the `AtlasMetadataEntrySheetValidationView` component. The key updates include dynamically generating metadata URLs using the portal configuration, ensuring proper URL formatting with the `slugify` library, and passing the `metadataUrl` as a prop to the `Alert` component.
* [`app/views/AtlasMetadataEntrySheetValidationView/components/ValidationReport/components/EntityValidationReport/entityValidationReport.tsx`](diffhunk://#diff-eda5f28a70e2dbc89b436107e937bf1069e36bfa6264f8be5a8f9410b7a59c76R6-R11): Integrated `useConfig` to retrieve the portal URL from the site configuration, constructed the `metadataUrl` dynamically, and passed it as a prop to the `Alert` component. …
=> fix: update metadata report link to data dictionary tier 1 (#732)

app/apis/catalog/hca-atlas-tracker/common/api.ts, app/components/Entity/components/common/Table/components/TableCell/components/EllipsisCell/constants.ts, app/components/Entity/components/common/Table/components/TableCell/components/EllipsisCell/ellipsisCell.tsx, app/components/Entity/components/common/Table/table.tsx, app/components/Entity/components/common/Table/types.ts, app/components/Table/options/visibility/constants.ts, app/views/AtlasMetadataCorrectnessView/atlasMetadataCorrectnessView.tsx, app/views/AtlasMetadataCorrectnessView/common/config.ts, app/views/AtlasMetadataCorrectnessView/common/constants.ts, app/views/AtlasMetadataCorrectnessView/components/Table/components/TableCell/components/GraphValueCell/constants.ts, app/views/AtlasMetadataCorrectnessView/components/Table/components/TableCell/components/GraphValueCell/graphValueCell.styles.ts, app/views/AtlasMetadataCorrectnessView/components/Table/components/TableCell/components/GraphValueCell/graphValueCell.tsx, app/views/AtlasMetadataCorrectnessView/components/Table/components/TableCell/components/GraphValueCell/utils.ts, app/views/AtlasMetadataCorrectnessView/components/Table/components/ToggleButtonGroup/constants.ts, app/views/AtlasMetadataCorrectnessView/components/Table/components/ToggleButtonGroup/entities.ts, app/views/AtlasMetadataCorrectnessView/components/Table/components/ToggleButtonGroup/toggleButtonGroup.styles.ts, app/views/AtlasMetadataCorrectnessView/components/Table/components/ToggleButtonGroup/toggleButtonGroup.tsx, app/views/AtlasMetadataCorrectnessView/components/Table/constants.ts, app/views/AtlasMetadataCorrectnessView/components/Table/entities.ts, app/views/AtlasMetadataCorrectnessView/components/Table/hooks/useTable/entities.ts, app/views/AtlasMetadataCorrectnessView/components/Table/hooks/useTable/hook.ts, app/views/AtlasMetadataCorrectnessView/components/Table/hooks/useTable/utils.ts, app/views/AtlasMetadataCorrectnessView/components/Table/table.styles.ts, app/views/AtlasMetadataCorrectnessView/components/Table/table.tsx, app/views/AtlasMetadataCorrectnessView/components/Table/utils.ts, app/views/AtlasMetadataCorrectnessView/components/Tables/tables.styles.ts, app/views/AtlasMetadataCorrectnessView/components/Tables/tables.tsx, app/views/AtlasMetadataCorrectnessView/components/Tables/utils.ts, app/views/AtlasMetadataCorrectnessView/entities.ts, app/views/AtlasMetadataCorrectnessView/hooks/useFetchMetadataCorrectness.ts
Closes #729.
This pull request introduces the new "Atlas Metadata Correctness" feature, which provides a heatmap-based view of metadata correctness for atlas entry sheets. The changes span backend data aggregation, API extensions, and frontend UI components to support interactive, color-coded tables with tooltips and access control. Below are the most important changes grouped by theme.
**Backend and API Enhancements**
* Added a new API endpoint `ATLAS_METADATA_CORRECTNESS` to the `API` enum for retrieving atlas heatmap data.
* Implemented the `getAtlasHeatmap` service and supporting types (`Heatmap`, `HeatmapClass`, etc.) to compute and return metadata correctness heatmaps based on entry sheet validations and the data dictionary. …
=> feat: metadata completeness heatmap (#729)

app/components/Detail/components/ViewAtlas/components/Tabs/tabs.tsx
Closes #752.
This pull request makes a minor update to the `Tabs` component by renaming a tab label from "Integration Objects" to "Integrated Objects" for improved clarity and consistency.
* Renamed the tab label from "Integration Objects" to "Integrated Objects" in the `Tabs` component (`tabs.tsx`).
=> feat: rename tab to 'integrated objects' (instead of integration objects) (#752)

__tests__/api-atlases-id-component-atlases-id-source-datasets-id.test.ts, __tests__/api-atlases-id-component-atlases-id-source-datasets.test.ts, __tests__/api-atlases-id-component-atlases-id.test.ts, __tests__/api-atlases-id-component-atlases.test.ts, app/apis/catalog/hca-atlas-tracker/common/backend-utils.ts, app/apis/catalog/hca-atlas-tracker/common/entities.ts, app/components/Detail/components/ViewSourceStudiesSourceDatasets/viewSourceStudiesSourceDatasets.tsx, app/services/atlases.ts, app/services/component-atlases.ts, app/services/files.ts, app/services/s3-notification.ts, app/services/source-datasets.ts, db_scripts/generate-test-files.ts, pages/api/atlases/[atlasId]/component-atlases.ts, pages/api/atlases/[atlasId]/component-atlases/[componentAtlasId].ts, testing/constants.ts, testing/db-utils.ts, testing/entities.ts, testing/utils.ts
Closes #753
Still needs updated tests, and may need some attention after #756 is merged
Notes:
1. I didn't change existing field types on the API response, so some fields contain non-null but "empty" values, such as cell count being set to 0
1. I've created an enum for integrity status (among other type definitions), which I've also used for the `validationStatus` field -- not sure if that's the right choice
1. All integrated object APIs are updated to take file IDs instead of IDs for the `component_atlases` table
1. The dataset list API returns an empty array when there's no associated `component_atlases` entry (which is always at the moment), but attempting to link a dataset, which is still possible in the UI, will return an error
1. A simple solution to this might be to set the button …
=> feat: derive integrated object get api responses from files (#753)

app/components/Detail/components/ViewSourceStudies/constants.ts, app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts
Closes #795.
This pull request refactors how the source study datasets count column is built and displayed in the HCA Atlas Tracker catalog. The main changes simplify the code by removing an unused builder function, updating how the datasets count link is rendered, and adjusting table column definitions and visibility.
**Table configuration and column definition updates:**
* The `id` column is now included in the table columns and hidden by default in the table options, improving internal row identification while keeping the UI clean. [[1]](diffhunk://#diff-24930035ec067eda637648ac5f14156b9d7920ac216c35cc2c21800155e4531bL9-R9) [[2]](diffhunk://#diff-b40c9cfae34bbe2fe51e79be552b0af2ebf79552105c70236d5978760ebbe81aR1265-R1269)
**Source datasets count column refactor:**
* The …
=> feat: rename datasets used to datasets on alas source studies (#795)

app/components/Detail/components/ViewAtlas/components/Tabs/tabs.tsx, app/components/Detail/components/ViewAtlasSourceDatasets/viewAtlasSourceDatasets.tsx, app/components/Index/components/FileDownload/fileDownload.tsx, app/components/Index/components/FileDownload/utils.ts, app/components/Table/components/TablePlaceholder/tablePlaceholder.tsx, app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts
Closes #794.
This pull request updates the Atlas Tracker UI to enhance the Source Datasets tab and its table, and refactors the file download logic. The changes add a new "Source Datasets" tab, expand the table with new columns, and simplify the file download component, while also removing some unused or redundant code.
**Atlas Tracker UI Enhancements:**
* Added a new "Source Datasets" tab to the Atlas view and included a count of source datasets in the tab label. (`app/components/Detail/components/ViewAtlas/components/Tabs/tabs.tsx`) [[1]](diffhunk://#diff-1108c3d735aac7a45e5785895f31fe25f2f91e87827bcdc7a21d6d0a0f9d9e83L25-R30) [[2]](diffhunk://#diff-1108c3d735aac7a45e5785895f31fe25f2f91e87827bcdc7a21d6d0a0f9d9e83R55-R58)
* Expanded the Source Datasets table with new columns: "Created …
=> feat: add back source datasets tab to atlas (#794)

app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts
Closes #815.
This pull request updates how the cell count is displayed for source datasets in the HCA Atlas Tracker. The main change is to show an empty cell when the validation status is PENDING, rather than displaying a number.
**Enhancements to cell count display in source datasets:**
* Replaced the use of `getCellCountColumnDef` with a new `getSourceDatasetCellCountColumnDef` in the columns definition to provide custom rendering logic for cell counts.
* Added the `getSourceDatasetCellCountColumnDef` function, which specifies the use of a new cell renderer for the cell count column.
* Implemented the `renderSourceDatasetCellCount` function to display an empty string when the validation status is PENDING, and otherwise format the cell count as a localized number.
=> feat: source dataset column tweaks (#815)

__tests__/api-sns-with-s3-event.test.ts, __tests__/api-sns-with-validation-results.test.ts, __tests__/api-sns.test.ts, app/apis/catalog/hca-atlas-tracker/aws/schemas.ts, app/apis/catalog/hca-atlas-tracker/common/entities.ts, app/data/files.ts, app/services/sns-dispatcher.ts, app/services/validation-results-notification.ts, migrations/1757716803455_validation-results-columns.ts, testing/constants.ts, testing/db-utils.ts, testing/sns-testing.ts, testing/utils.ts
Closes #803
Notes:
- Updated the existing SNS tests to separate tests specific to S3 events from tests for the high-level SNS handling
- Moved some shared SNS testing code to a separate file
- Renamed the existing SNS test files to follow the convention of mirroring the API path
=> feat: handle validation result sns messages (#803)

__tests__/validator-batch.test.ts, app/services/validator-batch.ts, package-lock.json, package.json
This pull request introduces a new service for submitting AWS Batch jobs to validate datasets, along with corresponding tests and dependency updates. The main changes include implementing the `submitDatasetValidationJob` function, comprehensive unit tests for this functionality, and adding the AWS Batch SDK dependency.
**New AWS Batch validation job submission service:**
* Added `submitDatasetValidationJob` function in `app/services/validator-batch.ts`, which reads required environment variables, validates resource authorization, and submits a Batch job with appropriate environment overrides. The function is fully documented and supports dependency injection for easier testing.
* Introduced input validation for required environment variables and resource allowlisting using …
=> chore(batch): add validator batch submit service and tests (#834)

__tests__/api-atlases-id-component-atlases.test.ts, __tests__/api-atlases-id-source-datasets-id.test.ts, __tests__/api-atlases-id-source-datasets.test.ts, __tests__/api-atlases-id-source-studies-id-source-datasets-id.test.ts, __tests__/api-atlases-id-source-studies-id-source-datasets.test.ts, app/services/component-atlases.ts, app/services/source-datasets.ts, testing/constants.ts, testing/db-utils.ts, testing/entities.ts, testing/utils.ts
Closes #840
All queries that reference the files table for source dataset and integrated object APIs have been updated, except for the query for getting a specific integrated object, which takes a file ID and so can only ever return that specific file record
=> fix: use latest file version where unspecified for source dataset and integrated object apis (#840)

__tests__/api-atlases-id-component-atlases.test.ts, __tests__/api-sns-with-s3-event.test.ts, __tests__/api-sync-files.test.ts, app/apis/catalog/hca-atlas-tracker/common/constants.ts, app/data/files.ts, app/services/__mocks__/validator-batch.ts, app/services/s3-notification.ts, testing/constants.ts, testing/db-utils.ts
Closes #839
Notes:
- Validation is skipped when a file record is updated rather that being inserted (which I believe can only happen if there's a duplicate SNS message)
- Validation is also skipped when an older message arrives after a newer one. I'm not sure how useful this is though -- my thought was that since the validator just validates the latest version, we wouldn't want to save its results to a record for an older version, but what I've done here doesn't address the core issue, and we could still theoretically end up with a situation where the messages arrive in order but after multiple changes have already been made, in which case the validator *would* get called for an outdated version of the file
=> feat: start validation job when a file is added or updated (#839)

app/components/Detail/components/ViewSourceDatasets/viewSourceDatasets.tsx
Closes #774.
This pull request makes a small adjustment to the `ViewSourceDatasets` component by removing the unused `canEdit` property from both the access destructuring and the `TablePlaceholder` component. No functional changes are introduced; this is a cleanup to remove unnecessary code. [[1]](diffhunk://#diff-52ef7f19f386d1d673b069b99552ec314fc0c93d39dd7cf55932b46a7cc92b33L22-R22) [[2]](diffhunk://#diff-52ef7f19f386d1d673b069b99552ec314fc0c93d39dd7cf55932b46a7cc92b33L37)
=> fix: fix fallback message for empty integration objects and other similar pages (#774)

app/apis/catalog/hca-atlas-tracker/common/backend-utils.ts, app/apis/catalog/hca-atlas-tracker/common/entities.ts, app/services/component-atlases.ts, app/services/source-datasets.ts, testing/constants.ts, testing/db-utils.ts, testing/entities.ts, testing/utils.ts
Closes #863
The response differs slightly from what's specified in the ticket in that (as established in the PR adding the database column) I've used `overallValid` instead of `overall_valid`, since that's our convention in other JSON columns
=> feat: return validation summary from source dataset and integrated object apis (#863)

__tests__/api-atlases-id-component-atlases-id.test.ts, __tests__/api-atlases-id-source-datasets-id.test.ts, app/apis/catalog/hca-atlas-tracker/common/backend-utils.ts, app/apis/catalog/hca-atlas-tracker/common/entities.ts, app/services/component-atlases.ts, app/services/source-datasets.ts, app/views/AtlasSourceDatasetView/hooks/useFetchAtlasSourceDataset.ts, app/views/ComponentAtlasView/hooks/useFetchComponentAtlas.ts, pages/api/atlases/[atlasId]/component-atlases/[componentAtlasId].ts, pages/api/atlases/[atlasId]/source-datasets/[sourceDatasetId].ts, testing/constants.ts, testing/db-utils.ts, testing/entities.ts, testing/utils.ts
Closes #864
Notes:
- This only includes the atlas-based APIs (i.e. not the obsolete(?) source dataset APIs off of source studies and component atlases)
- I updated the types on `useFetchComponentAtlas` and `useFetchAtlasSourceDataset`, but not on anything that uses them (which works fine since the new types returned from the APIs are subtypes of the old types)
- The test data generation script already creates validation reports
=> feat: return validation reports from atlas source dataset and component atlas detail apis (#864)

app/components/common/Form/components/Select/constants.ts, app/components/common/Form/components/Select/select.tsx
Closes #851.
This pull request refactors the `Select` component in the form library to centralize and standardize its default props. The main improvement is the introduction of a `constants.ts` file to define shared select properties, making the codebase more maintainable and consistent.
Component standardization and maintainability:
* Created a new `constants.ts` file that defines a `SELECT_PROPS` object with default properties for the `Select` component, such as `fullWidth`, `size`, and customized `MenuProps` for consistent styling.
* Updated the `Select` component to import and use `SELECT_PROPS` instead of hardcoding these props, ensuring all instances of the component use the same defaults and making future updates easier. [[1]](diffhunk://#diff-e08383fdf3acf4697633c927b76c5a31669559a …
=> fix: fix select drop down shadow (#851)

app/components/Table/components/TableCell/components/ValidationStatusCell/components/ValidationSummary/entities.ts, app/components/Table/components/TableCell/components/ValidationStatusCell/components/ValidationSummary/validationSummary.tsx, app/components/Table/components/TableCell/components/ValidationStatusCell/entities.ts, app/components/Table/components/TableCell/components/ValidationStatusCell/validationStatusCell.tsx, app/viewModelBuilders/catalog/hca-atlas-tracker/common/viewModelBuilders.ts, app/views/AtlasSourceDatasetsView/components/Table/columns.ts, app/views/AtlasSourceDatasetsView/components/Table/viewBuilders.ts
Closes #899.
This pull request refactors the validation status cell components to support dynamic routing for validation summary links and improves type safety and reusability. The main changes involve updating the props and rendering logic of the `ValidationStatusCell` and `ValidationSummary` components, and ensuring that validation summary links now use the appropriate dynamic routes for both integrated objects and source datasets.
**Component and Type Refactoring:**
- Updated the `ValidationStatusCell` and `ValidationSummary` components to accept a `validationRoute` prop, enabling dynamic linking to validation summary pages. The `Props` types were revised to include this new property and improve type safety for usage with different data models. …
=> feat: link validation summary in tables to validation detail pages (#899)

__tests__/api-sns-with-validation-results.test.ts, app/apis/catalog/hca-atlas-tracker/aws/schemas.ts, app/apis/catalog/hca-atlas-tracker/common/constants.ts, db_scripts/generate-test-validation-results.ts, testing/sns-testing.ts
Closes #906
Saving the results to the database implicitly means that they show up in the APIs, since they're in the same JSONB columns as the CAP results
Also, it looks like the UI is already set up to to display all validators -- the only issue I noticed while briefly looking at it in the app was that in the "Validation Summary" column in the entity lists, both links go to the CAP report
=> feat: save cellxgene results in validation results and summary (#906)

__tests__/api-atlases-id-source-studies-id-source-datasets-create.test.ts, app/data/source-datasets.ts, app/services/source-datasets.ts, app/services/source-studies.ts
Closes #916
As suggested by the title, this only covers queries that are used to retrieve source datasets -- there are some other queries still left in `services/source-datasets.ts`
=> refactor: separate source dataset retrieval queries into data layer with less duplication (#916)
